import 'package:flutter/cupertino.dart';

const Color kbyoncolor1 = Color(0XFFD72441);
const Color kbyoncolor2 = Color(0XFF0A1F44);
const Color kbyoncolor3 = Color(0XFF12B24E);
const Color kbyoncolor4 = Color(0XFFEAECEF);
const Color kbyoncolor5 = Color(0XFFDB2F38);
const Color kbyoncolor6 = Color(0XFF414D55);
const Color kbyoncolor7 = Color(0XFF9FA1B3);
const Color kbyoncolor8 = Color(0XFFFB5A12);
const Color kbyoncolor9 = Color(0XFF1C1C1C);
const Color kbyoncolor10 = Color(0XFFB7B7B7);
const Color kbyoncolor11 = Color(0XFF000000);
const Color kbyoncolor12 = Color(0XFF1FC89C);
const Color kbyoncolor13 = Color(0XFFFB5A1F);
const Color kbyoncolor14 = Color(0XFFFD0D1B);
const Color kbyoncolor15 = Color(0XFF8E8E93);

const String kfontPoppinsExtraLightItalic = 'Poppins-ExtraLightItalic';
const String kfontPoppinsLightItalic = 'Poppins-LightItalic';
const String kfontPoppinsLight = 'Poppins-Light';
const String kfontRobotoRegular = 'Roboto-Regular';
// const String kfontPoppinsLight = 'Poppins-Light';
const String kfontPoppinsRegular = 'Poppins-Regular';
const String kfontRobotoBlack = 'Roboto-Black';
const String kfontRobotoBold = 'Roboto-Bold';
const String kfontPoppinsBold = 'Poppins-Bold';
const String kfontPoppinsMedium = 'Poppins-Medium';
const String kfontRubikMedium = 'Rubik-Medium';
const String kfontPoppinsSemiBold = 'Poppins-SemiBold';
// const String kfontPoppinsBold = 'Poppins-Bold';
